services:
  web:
    build: .
    command: gunicorn --config /app/gunicorn.conf.py --bind 0.0.0.0:8000 mysite.wsgi:application
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
      - migrate
      - collectstatic
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=0.0.0.0,localhost
    ports:
      - "80:8000"
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: evdatabase
      POSTGRES_USER: evuser
      POSTGRES_PASSWORD: evpassword
    ports:
      - "5432:5432"
    networks:
      - app-network

  migrate:
    build: .
    command: python manage.py migrate
    depends_on:
      - db
    networks:
      - app-network

  collectstatic:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput && chmod -R 755 /app/staticfiles"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - migrate
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles 
      - media_volume:/app/media
    ports:
      - "8000:80"
    depends_on:
      - web
    networks:
      - app-network

volumes:
  static_volume:
  media_volume:

networks:
  app-network:
  
